

use Flight_Analysis;
-- Create Tables

CREATE TABLE Airline (
AIRLINE_ID INT PRIMARY KEY,
UNIQUE_CARRIER VARCHAR(10),
UNIQUE_CARRIER_NAME VARCHAR(100),
UNIQUE_CARRIER_ENTITY VARCHAR(10)
);




CREATE TABLE Airport (
AIRPORT_ID INT PRIMARY KEY,
AIRPORT_SEQ_ID INT,
CITY_MARKET_ID INT,
AIRPORT_CODE VARCHAR(10),
CITY_NAME VARCHAR(100),
STATE_ABR CHAR(2),
STATE_FIPS INT,
STATE_NM VARCHAR(100),
WAC INT
);


 

CREATE TABLE FLIGHT (
FLIGHT_ID INT IDENTITY(1,1) PRIMARY KEY,
AIRLINE_ID INT,
ORIGIN_AIRPORT_ID INT,
DEST_AIRPORT_ID INT,
DISTANCE FLOAT,
DISTANCE_GROUP INT,
YEAR INT,
QUARTER INT,
MONTH INT,
CLASS CHAR(1),
FOREIGN KEY (AIRLINE_ID) REFERENCES Airline(AIRLINE_ID),
FOREIGN KEY (ORIGIN_AIRPORT_ID) REFERENCES Airport(AIRPORT_ID),
FOREIGN KEY (DEST_AIRPORT_ID) REFERENCES Airport(AIRPORT_ID)
);



CREATE TABLE FlightMetrics (
FLIGHT_ID INT,
PASSENGERS FLOAT,
FREIGHT FLOAT,
MAIL FLOAT,
FOREIGN KEY (FLIGHT_ID) REFERENCES Flight(FLIGHT_ID)
);




CREATE TABLE CITY (
CITYID INT IDENTITY(1,1) PRIMARY KEY,
CITYNAME VARCHAR(100),
STATE_ABR CHAR(2),
STATE_NM VARCHAR(100),
UNIQUE (CityName, State_ABR)
);



