

-- Insert Data into Tables

INSERT INTO Airline(AIRLINE_ID,UNIQUE_CARRIER,UNIQUE_CARRIER_NAME,UNIQUE_CARRIER_ENTITY)
SELECT
    AIRLINE_ID,
    MAX(UNIQUE_CARRIER),
    MAX(UNIQUE_CARRIER_NAME),
    MAX(UNIQUE_CARRIER_ENTITY)
FROM meta_data
WHERE AIRLINE_ID IS NOT NULL
GROUP BY AIRLINE_ID;

-- Some AIRLINE_IDs had inconsistent UNIQUE_CARRIER_ENTITY values.
-- MAX() was used to select one representative record for normalization.

-- Insert Origin Airport Data
INSERT INTO Airport (AIRPORT_ID, AIRPORT_SEQ_ID, CITY_MARKET_ID, AIRPORT_CODE, CITY_NAME, STATE_ABR, 
                     STATE_FIPS, STATE_NM,WAC)

SELECT DISTINCT
ORIGIN_AIRPORT_ID,
ORIGIN_AIRPORT_SEQ_ID,
ORIGIN_CITY_MARKET_ID,
ORIGIN,
ORIGIN_CITY_NAME,
ORIGIN_STATE_ABR,
ORIGIN_STATE_FIPS,
ORIGIN_STATE_NM,
ORIGIN_WAC
FROM meta_data;     



--Insert Destination Airport Data
INSERT INTO Airport (AIRPORT_ID, AIRPORT_SEQ_ID, CITY_MARKET_ID, AIRPORT_CODE, CITY_NAME, STATE_ABR, 
                     STATE_FIPS, STATE_NM,WAC)

SELECT DISTINCT
DEST_AIRPORT_ID,
DEST_AIRPORT_SEQ_ID,
DEST_CITY_MARKET_ID,
DEST,
DEST_CITY_NAME,
DEST_STATE_ABR,
DEST_STATE_FIPS,
DEST_STATE_NM,
DEST_WAC
FROM meta_data m
WHERE NOT EXISTS (
SELECT 1
FROM Airport a
WHERE a.AIRPORT_ID = m.DEST_AIRPORT_ID
);





INSERT INTO Flight (AIRLINE_ID, ORIGIN_AIRPORT_ID, DEST_AIRPORT_ID, DISTANCE, DISTANCE_GROUP, YEAR, QUARTER, MONTH,CLASS)
SELECT
   AIRLINE_ID,
   ORIGIN_AIRPORT_ID,
   DEST_AIRPORT_ID,
   DISTANCE,
   DISTANCE_GROUP,
   YEAR,
   QUARTER,
   MONTH,
   CLASS
FROM meta_data





INSERT INTO FlightMetrics (FLIGHT_ID, PASSENGERS, FREIGHT, MAIL)
SELECT
    f.FLIGHT_ID,
    m.PASSENGERS,
    m.FREIGHT,
    m.MAIL
FROM meta_data m
JOIN Flight f
  ON f.AIRLINE_ID = m.AIRLINE_ID
 AND f.ORIGIN_AIRPORT_ID = m.ORIGIN_AIRPORT_ID
 AND f.DEST_AIRPORT_ID = m.DEST_AIRPORT_ID
 AND f.YEAR = m.YEAR
 AND f.MONTH = m.MONTH
 AND f.QUARTER = m.QUARTER
 AND f.DISTANCE = m.DISTANCE;




INSERT INTO CITY ( CITYNAME, STATE_ABR, STATE_NM)
SELECT DISTINCT
      ORIGIN_CITY_NAME,
      ORIGIN_STATE_ABR,
      ORIGIN_STATE_NM
from meta_data





INSERT INTO CITY ( CITYNAME, STATE_ABR, STATE_NM)
SELECT DISTINCT
      DEST_CITY_NAME,
      DEST_STATE_ABR,
      DEST_STATE_NM
from meta_data
WHERE DEST_CITY_NAME NOT IN (
      SELECT CITYNAME FROM CITY
)

